
# robot cinematic parameters
min_linear_vel  : 0.01  # [m/s]  . > 0. The robot is considered to be stopped if issued velocity is lesser than this.
max_linear_vel  : 0.80  # [m/s]  . > 0. Used to enforce velocity constraints.
min_angular_vel : 0.01  # [m/s]  . > 0. The robot is considered to be stopped if issued velocity is lesser than this.
max_angular_vel : 0.80  # [rad/s]. > 0. Used to enforce velocity constraints.
linear_decel  : 0.20    # [m/s/s]. > 0. 0.3 is the nominal value for Pioneer 3AT
linear_accel  : 0.35    # [m/s/s]. > 0. 0.3 is the nominal value for Pioneer 3AT
angular_decel : 1.50    # [rad/s/s]. > 0. 1.74 is the nominal value for Pioneer 3AT
angular_accel : 2.00    # [rad/s/s]. > 0. 1.74 is the nominal value for Pioneer 3AT

# robot frames
base_frame       : "/bender/base_link"
laser_front_frame: "/bender/sensors/laser_front_link"
laser_rear_frame : "/bender/sensors/laser_rear_link"
laser_rgbd_frame : "/bender/sensors/rgbd_head_laser_link"

# times
control_rate: 10   # [Hz]. Keep it above 5Hz, but consider the highest sensor rate is 20Hz.
odom_timeout: 0.5  # [s]. How long it takes to consider the odometry to be obsolete.
cmd_timeout : 0.5  # [s]. How long it takes to consider the cmd_vel command to be obsolete.

# robot footprint and obstacle margins
# - this footprint is a simplification of the real footprint
# - it considers different sizes to check depending on the motion direction.
# - please be accurate, but do not understimate this.
# - padding values are added to the robot footprint in order to compute the inflation radius.
robot_width       : 0.66  # [m] Estimated robot width (y axis). 
robot_length_front: 0.25  # [m] Estimated robot length on x axis. From center to front most point.
robot_length_rear : 0.30  # [m] Estimated robot length on x axis. From center to rear most point.
padding_sides: 0.03  # [m] Minimum distance to obstacles on each side of the robot.
padding_rear : 0.20  # [m] Minimum distance to obstacles on the robot rear direction.
padding_front: 0.20  # [m] Minimum distance to obstacles on the robot front direction.

# misc
is_debug_enabled         : false # prints debug information.
is_visualization_enabled : true  # process markers for RVIZ. This can be a drawback on slower
                                 # systems or when the sensor resolution is too high.

max_obstacle_range  : 1.5   # [m] ignore obstacles outside this radius
sim_lookahead_factor: 2.0   # The velocity simulation will (de)increment the current
                            # velocity depending on the control_rate. This number is a multiplier
                            # for the velocity increment. It can be understood as how many control
                            # rates in the future to generate a velocity for. This must be > 0.
                            #
                            # PS. Using sim_lookahead_factor = control_rate means the to have a
                            # sim_time of 1 second!.
                            # Otherwise, the sim_time can be computed as:
                            #    control_rate / sim_lookahead_factor.
